### ISSUE TITLE
Lua Error

### ISSUE THREAD

**Issue by Teng3n** [silverhawke249/RearrangePetTab#1]
I seem to get this went logging in or hitting a load screen such as after hearthing.

> 77x RearrangePetTab\RearrangePetTab-1.2.lua:94: bad argument #1 to 'unpack' (table expected, got nil)
> [string "=[C]"]: in function `unpack'
> [string "@RearrangePetTab\RearrangePetTab-1.2.lua"]:94: in function `?'
> [string "@RearrangePetTab\RearrangePetTab-1.2.lua"]:216: in function <RearrangePetTab\RearrangePetTab.lua:214>
> 
> Locals:
> (*temporary) = nil
> (*temporary) = "table expected, got nil"

**Comment by silverhawke249** [comment]
Seems like an issue with ElvUI where the frame I intended to move/create has no size.
Can you try the latest `RearrangePetTab.lua` in the repo? If that fixes it, I'll push a new release.

**Comment by Teng3n** [comment]
That seems to have fixed it! Thank you!
